import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header/Header'



export default function Home( {data}:any ) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-Lightest col-span-full lg:col-start-3 lg:col-end-11 flex flex-col items-center justify-start'>
        <Header />

        {/* Subjects */}
        <div className='w-full flex flex-col justify-start items-start'>

          <h1 className='text-4xl text-Dark font-nunito font-bold'> Subjects - {data}</h1>




        </div>

      </main>
    </>
  )
}


export async function getServerSideProps () {

  const data = "W"
  return {
    props: {data}
  }
}